language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      compiler: clang
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc
    - os: osx
      osx_image: xcode8.3

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt58-trusty'
    packages:
    - qt58-meta-minimal
    - qt58svg
    - qt58tools
    - openvpn

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt58/bin/qt58-env.sh; fi

script:
  - qmake
  - make
